'use strict';requireRole('admin');let registros=[];
function message(t,error=false){$('#mensaje').textContent=t;$('#mensaje').className=`message ${error?'error':''}`}
function filtrados(){const q=$('#filtroTexto').value.toLowerCase(),e=$('#filtroEstado').value;return registros.filter(x=>(!q||[x.codigo,x.estudiante,x.carrera].some(v=>String(v||'').toLowerCase().includes(q)))&&(!e||x.estado===e))}
function render(){const rows=filtrados();$('#registrosBody').innerHTML='';rows.forEach(x=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(x.codigo)}</td><td>${esc(x.estudiante)}</td><td>${esc(x.carrera)}</td><td>${esc(x.fechaUso||'-')}</td><td>${esc(x.horarioUso||'-')}</td><td>${money(x.total)}</td><td></td><td><button class="secondary detalle">Ver</button></td>`;const s=document.createElement('select');s.className='status';['Pendiente','Aprobada','En proceso','Finalizada','Rechazada','Cancelada'].forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;o.selected=v===(x.estado||'Pendiente');s.appendChild(o)});s.addEventListener('change',async()=>{try{await api({action:'estado',codigo:x.codigo,estado:s.value});x.estado=s.value;message(`Estado de ${x.codigo} actualizado.`);actualizarKpi()}catch(e){message(e.message,true)}});tr.children[6].appendChild(s);tr.querySelector('.detalle').addEventListener('click',()=>verDetalle(x));$('#registrosBody').appendChild(tr)});if(!rows.length)$('#registrosBody').innerHTML='<tr><td colspan="8">No existen registros con esos filtros.</td></tr>';actualizarKpi()}
function actualizarKpi(){$('#kpiSolicitudes').textContent=registros.length;$('#kpiPendientes').textContent=registros.filter(x=>x.estado==='Pendiente').length;$('#kpiTotal').textContent=money(registros.reduce((a,x)=>a+Number(x.total||0),0))}
async function load(){try{message('Cargando solicitudes...');const r=await api({action:'listar'});registros=r.registros||[];render();message('Solicitudes actualizadas.')}catch(e){message(e.message,true)}}
function verDetalle(x){const items=(x.items||[]).map(i=>`<li>${esc(i.concepto)}: ${esc(i.cantidad)} ${esc(i.unidad)} × ${money(i.precio)}</li>`).join('')||'<li>Sin materiales registrados</li>';$('#detalleContenido').innerHTML=`<div class="detail-grid"><p><strong>Código:</strong> ${esc(x.codigo)}</p><p><strong>Estudiante:</strong> ${esc(x.estudiante)}</p><p><strong>Identificación:</strong> ${esc(x.identificacion)}</p><p><strong>Código estudiantil:</strong> ${esc(x.codigoEstudiante)}</p><p><strong>Carrera:</strong> ${esc(x.carrera)}</p><p><strong>Semestre:</strong> ${esc(x.semestre)}</p><p><strong>Correo:</strong> ${esc(x.correo)}</p><p><strong>Teléfono:</strong> ${esc(x.telefono)}</p><p><strong>Docente:</strong> ${esc(x.docente)}</p><p><strong>Asignatura:</strong> ${esc(x.asignatura)}</p><p><strong>Fecha y horario:</strong> ${esc(x.fechaUso)} · ${esc(x.horarioUso)}</p><p><strong>Proyecto:</strong> ${esc(x.tipoProyecto)}</p></div><p><strong>Descripción:</strong> ${esc(x.descripcion)}</p><p><strong>Herramientas:</strong> ${esc(x.herramientas)}</p><h3>Materiales</h3><ul>${items}</ul><p class="dialog-total"><strong>Total:</strong> ${money(x.total)}</p>`;$('#detalleDialog').showModal()}
function csv(){const rows=filtrados(),headers=['Código','Estudiante','Carrera','Fecha','Horario','Proyecto','Total','Estado'];const data=[headers,...rows.map(x=>[x.codigo,x.estudiante,x.carrera,x.fechaUso,x.horarioUso,x.tipoProyecto,x.total,x.estado])];const content=data.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const blob=new Blob(['\ufeff'+content],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`reporte-taller-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
$('#btnActualizar').addEventListener('click',load);$('#filtroTexto').addEventListener('input',render);$('#filtroEstado').addEventListener('change',render);$('#btnCSV').addEventListener('click',csv);$('#btnImprimir').addEventListener('click',()=>window.print());$('#cerrarDialog').addEventListener('click',()=>$('#detalleDialog').close());load();
